export enum RailOrderStatus {
    DRAFT = "DRAFT",
    WAITING = "WAITING",
    TRANSMITTED = "TRANSMITTED",
    EXPIRED = "EXPIRED",
    CAPTURED = "CAPTURED",
    ACCEPTED = "ACCEPTED",
    SUBMITTED = "SUBMITTED",
    ACTIVE = "ACTIVE",
    CLOSED = "CLOSED",
    CANCELLED = "CANCELLED",
    INVALID = "INVALID"
  }