export interface Problem {
    // title: An RFC7807 problem object  type: object
    // errorCode: type: string description: An error number identifying the error  
    errorCode?: string
    // type: type: string format: uri-reference description: A URI reference that identifies the problem type.
    type?: string
    // title: type: string description: 'A short, human-readable summary of the problem type.'
    title?: string
    // status: type: integer description: >-  The HTTP status code generated by the origin server for this occurrence of  the problem. minimum: 100 maximum: 599
    status?: number
    // detail: type: string description: A human-readable explanation specific to this occurrence of the problem.
    detail?: string
    // instance: type: string format: uri-reference description: >-  A URI reference that identifies the specific occurrence of the problem. It  may or may not yield further information if dereferenced.
    instance?: string
    // errors: type: array items: $ref: '#/components/schemas/Error'
    errors?: ErrorObject[]
}

export interface ErrorObject {
    // errorCode: type: string description: An error number identifying the error
    errorCode?: string
    // title: type: string description: 'A short, human-readable summary of the problem type.' 
    title?: string
    // field: type: string description: Name of field that failed validation. 
    field?: string
    // detail: type: string description: A human - readable explanation specific to this occurrence of the problem.
    detail?: string
    // LocalDateTime: pattern: '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}$'description: Local date - time in the format YYYY - MM - DDTHH: MM: SS(e.g., 2024-06 - 25T14: 30:00)
    LocalDateTime?: string
}
