
import { WagonTrackingHistory, WagonEventType, InfrastructureLocation } from "../models/api-wagon-tracking-history.model";

export class ApiTrackingHistoryWagonMocks {
    private trackingHistoryWagon = new Array();
    private mockWagonNumbers = ['218033010081', '892050695808', '238074751104', '318053609943', '378053363933'];
    private wagonEventType = ['DEPARTURE', 'ARRIVAL', 'PASS_THROUGH', 'HANDOVER','TAKEOVER', 'ACTIVATION', 'COMPLETION'];
    private mockCity: string[] = ['BOCHUM', 'SALZGITTER', 'MUSTERSTADT', 'SCHIRNDING', 'KINDBERG-AUMÜHL', 'DUISBURG (-NEUENKAMP)', 'DÜSSELDORF', 'SALZBURG', 'GRÄFELFING', 'DINAZZANO', 'DIEKHOF', 'KNUROW', 'UNTERWELLENBORN', 'DESIO', 'ESSINGEN', 'OBERRIEXINGEN', 'FRANKFURT A.M', 'SCHWEINFURT', 'ALFELD/LEINE', 'MÜNSTER', 'BÖNEN', 'PLATTLING', 'BOTTROP', 'FELDKIRCH-TOSTERS', 'BIELEFELD', 'BOEHLEN', 'BEESKOW', 'SCHWARZ', 'RHEINBERG', 'PORAJ', 'SALZBERGEN', 'PLOCHINGEN', 'GLATTBRUGG RÜMLANG', 'MÖCKMÜHL-ZÜTTLINGEN', 'LANGELSHEIM', 'KÖLN-DEUTZ', 'MARSCHACHT', 'VILLERS-COTTERETS', 'PERPIGNAN', 'QUERFURT', 'WORMS', 'OSTERHOFEN', 'LAUßIG B. DÜBEN', 'STRAUBING', 'NECKARSULM', 'GERNSHEIM', 'MADRID', 'LINZ, DONAU', 'SACHSENHEIM', 'HARSEFELD', 'AARAU', 'STOCKHOLM', 'HERSCHBACH', 'ZAWIERCIE', 'KÖLLEDA', 'STEINBACH AM WALD', 'FRANKFURT/M', 'IMOWROCLAW', 'BERGKAMEN', 'TALLINN', 'GINSHEIM-GUSTAVSBURG', 'VILLERS COTTERETS', 'STEYERBERG', 'HERINGEN', 'MOOSBURG', 'SORNZIG - ABLAß', 'BAD DRIBURG', 'NEUMARKT, OBERPF', 'STEINAU AN DER STRAßE', 'BAD TÖLZ', 'SWARZEDZ', 'BOZHURISTE (SOFIA)', 'KOBYLNICA', 'BAD HARZBURG', 'DINGOLFING', 'VILLACH', 'OSWIECIM', 'PARTHENSTEIN OT GROßSTEINB', 'DOHNA', 'DIEPHOLZ', 'SAN SALVO', 'PRAHA 4', 'STADTOLDENDORF', 'KISSING', 'MARTORELL', 'GLAUCHAU', 'PERLEN (BEI LUZERN)', 'WALS B. SALZBURG', 'LAUTERBACH', 'MAUREN', 'LIBCANY', 'MARIBEL', 'ELSTERAUE OT ALTTRÖGLITZ', 'MÜNSTER/WESTF.', 'ESSEN-VOGELHEIM', 'WEIHERHAMMER', 'GROßRUDESTEDT', 'GÖTEBORG', 'DUBLIN', 'LONDON', 'VOBARNO', 'ESSINGEN WÜRTT', 'ZZRALCCEEDNNORUUTRALCCEEDNNORUUT', 'WERDAU', 'ADNET', 'SINGEN (HOHENTWIEL)', 'WISMAR', 'HALLE', 'SIMBACH', 'LENGERICH', 'BYDGOSZCZ', 'ZDZIESZOWICE', 'OSNABRÜCK', 'WITTEN (HERBEDE)', 'ARNSTADT', 'SIMBACH A. INN', 'LANDSHUT', 'HENGERSBERG', 'AICHSTETTEN', 'FRANKFURT/MAIN', 'RÜDERSDORF', 'SPIJKENISSE', 'BASEL', 'OSTRAVA', 'BRUNSBÜTTEL', 'TRAUNSTEIN', 'CREUZBURG', 'WLOCLAWEK', 'LÜBECK', 'MINDEN (WESTF)', 'NEUKIRCHEN', 'ESCHBORN (TAUNUS)', 'BUCHS SG', 'MEITINGEN', 'NOWE SKALMIERZYCE', 'BURBACH-HOLZHAUSEN', 'WALS-SIEZENHEIM', 'BIELSKO- BIALA', 'LUDWIGSBURG', 'GROßMEHRING', 'TRAUNREUT', 'ROSSLAU/ELBE', 'BONNIERS', 'RAKOVNIK', 'LÖHNE-GOHFELD', 'GARCHING/ALZ', 'HENNIGSDORF', 'MUKRAN', 'EBERSWALDE', 'GABLINGEN', 'OBERSTDORF', 'REUTH B PLAUEN', 'NEUNKIRCHEN', 'SREM UL MICKIEWICZA', 'IFFEZHEIM', 'OBERBIBB', 'BARSINGHAUSEN', 'DELMENHORST', 'ARAVACA (MADRID)', 'PORUBA', 'SEEKIRCHEN', 'BOCHUM-LAER', 'RENNES', 'CHATEAUDUN CEDEX', 'KEHL AM RHEIN', 'VILLERS COTTERELS', 'OSCHATZ', 'GDANSK', 'WESEL', 'WÖRTH', 'WITTGENSDORF', 'BAD SCHUSSENRIED', 'DETMOLD-REMMIGHAUSEN', 'DÜLMEN', 'OSTRAVA-KUNCICE', 'ASPERG', 'X= FELD 7 IDENTISCH SEIN', 'ALBBRUCK', 'GROßKOSCHEN', 'GOLENIOV', 'HERINGEN (WERRA)', 'FREIBERG', 'CRAILSHEIM', 'OBERNDORF IN TIROL', 'LIPTOVSKY MIKULAS', 'SAN ZENO FOLZANO', 'TROGLY BREUL', 'DABROWA', 'VILLERES COTTERETS', 'GROßSCHIRMA', 'KLEIN WANZLEBEN', 'RAVENSBURG', 'SCHÖNEBECK (ELBE)', 'AULNOYE - AYMERIES', 'PREMNITZ', 'BOXBERG', 'DELITZSCH', 'SAALBURG-EBERSDORF', 'GLADBECK', 'KASSEL', 'INGOLSTADT', 'BRUSSELS', 'RATINGEN', 'N?RNBERG', 'DRESDEN', 'NAGOLD', 'EISENHÜTTENSTADT', 'STADE', 'RHEINMÜNSTER', 'BUCHS / SG', 'STOCKSTADT AM MAIN', 'BLANKENSTEIN (SAALE)', 'MARKTBREIT', 'BRAKE', 'AALST', 'BRUXELLES', 'DORSTEN (-WULFEN)', 'SIEGELSBACH', 'BAUNATAL', 'BERLIN', 'DARMSTADT', 'QUIERSCHIED', 'STUTTGART (BAD CANNSTATT)', 'MARIA ANZBACH', 'AUGSBURG', 'POPPENDORF', 'NÜNCHRITZ', 'HAMELN', 'KLAGENFURT', 'ESSINGEN B. AALEN/WÜRTT', 'HERBERTINGEN', 'BRANDENBURG', 'MENZNAU', 'HUERTH', 'PRAHA', 'DIFFERDANGE', 'ENNEPETAL', 'WIESBADEN', 'LOVERE (BERGAMO)', 'RÜBELAND', 'GERETSRIED', 'SORCY ST MARTIN', 'NEUMARKT', 'ESCH / BELVAL', 'NETPHEN', 'SCHÖNTEICHEN', 'LAATZEN', 'KRAKOW', 'PARIS CEDEX 17', 'STEIMBKE', 'MÜHLHAUSEN-EHINGEN', 'HERTEN', 'KIRCHHEIM/TECK', 'HILCHENBACH', 'SOFIA', 'ZEEBRUGGE', 'MEPPEN', 'WÜLFRATH', 'BOLZANO', 'YVES-GOMEZEE', 'MARKTREDWITZ', 'KAARST', 'FLORANGE', 'TROSLY BREUL', 'FELDKIRCHEN', 'WARSZAWA', 'KEMPEN', 'OSTRAVA  KUNICE', 'WILHELMSHAVEN', 'BÜTZOW', 'GENOVA (GE)', 'SCHONGAU', 'WESTERLAND', 'DILLINGEN (SAAR)', 'AMSTERDAM', 'OSTRAVA KUNCICE', 'STRASSWALCHEN', 'INGOLSADT', 'COEVORDEN', 'TERNI', 'MSZCZONOW', 'VICENZA', 'LAMPERTSWALDE', 'OLDENBURG', 'LUTHERSTADT WITTENBERG', 'GREPPIN', 'TRITTAU', 'BRÜHL', 'ROTTENBURG', 'ETTRINGEN', 'RUDA SLASKA', 'SEELZE', 'LALENDORF', 'MÖRFELDEN-WALLDORF', 'LUBAWA', 'MERENBERG', 'KIRCHHEIM-HEIMSTETTEN', 'LUTHERSTADT - WITTENBERG', 'AINRING', 'PADOVA', 'SASSNITZ-MUKRAN', 'BRÖNDBY', 'EMSDETTEN', 'BRANDENBURG/KIRCHMÖSER', 'BASSANO DEL GRAPPA (VI)', 'HAMM (WESTF.)', 'NAVE BRESCIA', 'MAINTAL', 'GERNSBACH', 'VALLESE DI OPPEANO', 'DIFFERANGE', 'K E H L', 'COUNTRY DUBLIN', 'FRANKFURT (ODER)', 'KASSEEDORF', 'RÖVERSHAGEN', 'DORNBURG - LANGENDERNBACH', 'KR SITTARD', 'FÜRSTENZELL', 'JUCKEN', 'NIEDERSACHSWERFEN', 'MAGDEBURGÝÝ', 'MILANO (MI)', 'UTRECHT', 'WOLFSBURG', 'ESSEN', 'IPHOFEN', 'PEINE', 'SENNFELD', 'ILSENBURG', 'BITTERFELD-WOLFEN', 'ADELEBSEN', 'LEUNA', 'RYBNIK', 'WOLNZACH', 'ÜBERHERRN', 'MILANO', 'BREMEN', 'BRAKE (UNTERW)', 'AUGSBURG, BAY', 'BRUCHSAL', 'FRANKFURT AM MAIN', 'GEORGSDORF', 'SCHWEDT (ODER)', 'SPREMBERG', 'GERSTHOFEN', 'ALT ZACHUN', 'LANGEN', 'PAMPLONA', 'EVIAN-LES-BAINS', 'WÜRZBURG', 'ELXLEBEN', 'EHINGEN (DONAU)', 'KÄBSCHÜTZTAL/ MEHREN', 'SITTARD', 'KREFELD', 'NEUSS', 'PRAHA 7 HOLESOVICE', 'BREMERHAVEN', 'BUTZBACH', 'POLKOWICE', 'FRECHEN', 'GROß OESINGEN', 'THAYNGEN', 'BOBINGEN', 'DETMOLD', 'ZÖRBIG', 'KALLITHEA', 'KETZERBACH', 'NEUHOF', 'CZESTOCHOWA', 'RAVENNA', 'DOMAT/EMS', 'LIMBURG (LAHN)', 'BRILON', 'OFFENBURG', 'SIMBACH/INN', 'SWIECIE', 'ZEITHAIN', 'VISSELHÖVEDE', 'NORDHAUSEN', 'TREBSEN', 'ATHEN', 'MUHLHOUSE', 'KOLIN', 'MINDEN', 'REMSCHEID', 'PULLACH', 'VÖHRINGEN', 'GARDELEGEN', 'GRENZACH- WYHLEN', 'SOSNOWIEC', 'BURBACH', 'GLIWICE', 'HILDEN', 'DBROWA GORNICZA', 'GRISIGNANO DI ZOCCO (VI)', 'PREDOSA (ALESANDRIA)', 'FRIEDRICHSHAFEN', 'HALTERN', 'WROCLAW', 'HILDESHEIM', 'MUTTENZ', 'PEITZ', 'GROßEN BUSECK', 'ALTENSTEIG', 'WEISENHEIM AM BERG', 'OßLING', 'KREUZLINGEN', 'BRAUNSCHWEIG', '¡£¥¦©ª«¬¢¯±²³Μ¶·¹º»¼½¾¿ÀÃÅÆÈÊÌÏÑÒÕØ', 'KARLSRUHE', 'WESSELING', 'NEUWIED', 'STUTTGART', 'MANNHEIM', 'LEVERKUSEN', 'SEESEN-MÜNCHEHOF', 'ALZENAU', 'EMLEBEN', 'MÜLHEIM AN DER RUHR', 'BERNBURG', 'SCHWANDORF', 'HARTMANNSDORF', 'TASTRUP', 'VOELKLINGEN', 'BIRSFELDEN BL', 'BRIESELANG', 'SIEGEN', 'PORT-BOU GIRONA', 'MALMÖ', 'BURGHAUSEN', 'EBERBACH', 'EISENACH', 'GELSENKIRCHEN', 'DABROWA GORNICZA', 'KORBACH', 'BÖBLINGEN', 'CZESTOCHOWA POLSKA', 'DUDELANGE', 'SAARBRÜCKEN', 'BREITENBACH', 'WETZLAR', 'KERKEN', 'KUEHBACH', 'DILLINGEN', 'ELSTERAUE OT. TRÖGLITZ', 'FENSTERBACH', 'OCHSENFURT', 'VÖLKLINGEN', 'HAGENDORN-CHAM', 'BÖHLEN', 'DESIO (MI)', 'EILENBURG', 'ÜBERSYREN', 'K?BENHAVN SV', 'BARUTH/ MARK', 'SCHWELM', 'ESCHWEILER', 'BAD SAULGAU', 'SCHWERTE', 'HEILIGENGRABE', 'STOCKSTADT', 'WITTINGEN', 'RANSBACH-BAUMBACH', 'GÖTTINGEN', 'NIEDERKASSEL', 'LODYGOWICE', 'LUDWIGSFELDE', 'HÖHR-GRENZHAUSEN', 'GLESIEN', 'BUGHAUSEN', 'WÜNSCHENDORF', 'UNTERFÖHRING', 'POZNAN', 'GENEVA 15', 'EHINGEN', 'UNNA-KÖNIGSBORN', 'NORDHORN', 'SAINT-MALO CEDEX', 'KULMBACH', 'ZWICKAU', 'KELHEIM', 'FRANKFURT MAIN', 'STEINHEIM', 'MARL-HÜLS', 'COSWIG', 'ASCHAU AM INN', 'KORNWESTHEIM', 'KODERSDORF', 'MÝSLOWICE SWIERCZYNY', 'SINZIG/RHEIN', 'NACHTERSTEDT', 'MÜLHEIM(RUHR)', 'ANKLAM', 'PASSAU', 'SIGMARINGEN', 'RÜSSELSHEIM', 'CHEMNITZ', 'BERGEN', 'GÜNZBURG', 'SELTERS', 'COLLECCHIO', 'MILEVSKO', 'IMMELBORN', 'GRENZACH-WYHLEN', 'KIRCHHEIM/NECKAR', 'SAAL (DONAU)', 'VOERDE', 'COTTBUS', 'KEMPTEN', 'HEIDENHEIM', 'LOWYN', 'EGGENSTEIN- LEOPOLDSHAFEN', 'SANT PRIEST', 'NEU-ISENBURG', 'WIRGES', 'ZÜRICH', 'OBERURSEL', 'MÜNSCHEN', 'FRANKFURT', 'UETERSEN', 'DETTINGEN/TECK', 'WALDKRAIBURG', 'RYDULTOWY', 'ROSENTHAL AM RENNSTEIG', 'ST DENIS', 'GRATKORN', 'ZWENTENDORF', 'STOCKERAU', 'FINNENTROP', 'KREUZTAL', 'HAMBURG', 'UETZE', 'ESSINGEN,WÜRTT', 'KRAILLING', 'DINSLAKEN', 'BURGKIRCHEN', 'RIESA', 'SCHKOPAU', 'SINGEN', 'MOERS', 'BAD NEUSTADT', 'GEORGSMARIENHÜTTE', 'LANGENENSLINGEN', 'HAJNOWKA', 'BIELEFELD (BRACKWEDE)', 'WEIßENHORN', 'ANDERNACH', 'SZCZECIN', 'GEESTE - GR. HESEPE', 'RECKLINGHAUSEN', 'LIESKE', 'DILLENBURG', 'PLETTENBERG', 'STEINSFELD', 'LAMPERTHEIM', 'MÜNCHSMÜNSTER', 'TRIER-EHRANG', 'VOHBURG', 'HAMMERAU', 'NEUMÜNSTER', 'ZEITZ', 'MALMOE', 'LÜCHOW (WENDLAND)', 'MENDEN', 'SCHIFFLANGE', 'GB UTRECHT', 'OSTSTEINBECK', 'NORDENHAM', 'IRUN (GIUPUZCOA)', 'BUCHS', 'SAN GIUSTO C.SE (TO)', 'KÖSCHING', 'FREIBURG', 'GÜSEN', 'BAD LANGENSALZA', 'NAPAJEDLA', 'TROSTBERG', 'BERGHEIM-NIEDERAUßEM', 'WALBRZYCH', 'ANTWERPEN', 'KRIFTEL', 'DURMERSHEIM', 'MLADA BOLESLAV', 'STAFFORD', 'BRATISLAVA', 'KOSICE', 'UELZEN', 'BLAUBEUREN', 'LAUCHRINGEN', 'DABROWIE', 'LUCKENWALDE', 'WESTERLAND / SYLT', 'FREIBURG (BREISG)', 'NYBORG', 'VOLVIC (FRANCE)', 'KIRCHZELL', 'WEIL AM RHEIN', 'MAXHÜTTE-HAIDHOF', 'MEMMINGEN', 'PARIS CEDEX 08', 'ERNDTEBRÜCK', 'MÜLHEIM (RUHR)', 'TREUEN', 'SINDELFINGEN', 'PLZEN', 'ZUZGEN', 'RUDOLSTADT-SCHWARZA', 'KAMENZ/WIESA', 'KALISZ', 'GROß ÖNSINGEN', 'GÜNZACH', 'ZG PERNIS RT', 'PRAHA 10', 'WIENER NEUDORF', 'NÜRNBERG', 'DORTMUND', '(POSTFACH FÜR FERNDORF )', 'GÜTERSLOH', 'FREILASSING', 'KELSTERBACH', 'SCHLÜCHTERN', 'CLAIRVAUX', 'MÜLHEIM A. D. RUHR', 'ROSTOCK', 'KOLISZ', 'MONCALIERI', 'DEIßLINGEN (NECKAR)', 'VILLERS-COTTERETS CEDEX', 'BITTERFELD', 'HAMM (WESTF)', 'SCHWARZHEIDE', 'FRANKFURT (MAIN)', 'MÜNCHEN', 'GAGGENAU', 'CUXHAVEN', 'HANAU', 'ASCHAFFENBURG', 'FÜRNITZ', 'HEILBRONN', 'EPPINGEN', 'GOSLAR', 'MÜLHEIM A.D. RUHR', 'TRNAVA', 'WEIDEN I. D. OPF.', 'ANTWERPEN 4', 'BRZEG DOLNY', 'BORKEN', 'LINGEN', 'SCHWEDT/ODER', 'EMMERICH', 'SOUTHAMPTON', 'DORMAGEN', 'SULZBACH-ROSENBERG', 'ESCH BELVAL', 'DÜREN', 'PARIS', 'BÜLSTRINGEN', 'NOVI LIGURE (AL)', 'FELLBACH', 'FULDA', 'NUßDORF AM HAUNSBERG', 'KEDZIERZYV KOZLE', 'LUDWIGSHAFEN-RHEINGÖNNHEIM', 'SALZGITTER-BEDDINGEN', 'ISERLOHN', 'EMDEN', 'WEYHE-KIRCHWEYHE', 'MÜLHEIM/RUHR', 'WILRIJK(ANTWERPEN)', 'KAISERSLAUTERN', 'AACHEN', 'NORDERSTEDT', 'MESCHEDE', 'WUNSIEDEL', 'MARTINSRIED/PLANEGG', 'SPEYER', 'ORBASSANO (TO)', 'CAROUGE / GENEVE 26', 'HIRSCHAU', 'CASTROP-RAUXEL', 'LANDABEN', 'UNTERDIETFURT', 'EAUZE', 'BAD HONNEF', 'RIMPAR', 'C/O VWT   I.HS.AUDI AG ING', 'OCHSENHAUSEN', 'LIPPSTADT', 'BIANCONESE DI FONTEVIVO', 'RAUBLING', 'ELTMANN', 'GOTTENHEIM', 'KOBENHAVN SV', 'BREITENGÜßBACH', 'GREIZ', 'SCHWALMTAL- STORNDORF', 'AK VLISSINGEN', 'BOUS (SAAR)', 'BEDZIN', 'ARNHEM', 'RINGSTED', 'DONAUWÖRTH', 'PHILIPPSTHAL (WERRA)', 'WERDOHL', 'MERKENDORF', 'STRASBOURG', 'KATAOWICE', 'LÜBECK-SCHLUTUP', 'ROHRDORF', 'SASSNITZ/NEU MUKRAN', 'AE EDE', 'VERONA', 'DOBOJ', 'ST. JOHANN IN TIROL', 'BURGKIRCHENQ', 'KOPER', 'MAGDEBURGEUR', 'DUISBURG', 'MAINZ', 'HATTINGEN', 'HANNOVER', 'LUDWIGSHAFEN AM RHEIN', 'FLÖRSHEIM', 'LUDWIGSHAFEN (RHEIN)', 'KK PERNIS', 'OBERHAUSEN', 'BIEBESHEIM', 'REGENSBURG', 'RHEINFELDEN', 'LEIPZIG', 'FLAXWEILER', 'RADEBEUL', 'BORLÄNGE', 'WERK BÖHLEN/SCHKOPAU', 'TRELLEBORG', 'OFTRINGEN', 'EBELEBEN', 'LOHFELDEN', 'IBBENBÜREN', 'LINSENGERICHT', 'PADERBORN', 'HAGEN', 'ETTRINGEN, WERTACH', 'LUDWIGSHAFEN', 'IJMUIDEN', 'HOYERSWERDA', 'CADOLZBURG', 'ESCHBORN', 'CREMONA', 'ROSENHEIM', 'MINDEN (WESF.)', 'EUSKIRCHEN', 'DORNBURG-LANGENDERNBACH', 'ERFURT', 'WITTENBERGE', 'ASCHAU A. INN', 'COURBEVOIE CEDEX', 'NEUHAUSEN OB ECK', 'HÜRTH', 'HERNE', 'RUESSELSHEIM', 'OLECKO', 'OELSNITZ (VOGTLAND)', 'IRUN (GIUPÚZCOA)', 'ZWIERZYNIEC', 'BIELSKU-BIALA', 'PUDERBACH', 'GIENGEN', 'OBERHAUSEN (BAY)', 'HERBRECHTINGEN', 'NEU-ULM', 'STETI', 'ARAVACA', 'FLECHTINGEN', 'GAZOLDO DEGLI IPPOLITI', 'KÜSSNACH', 'HEIDENHEIM-MERGELSTETTEN', 'ESCHBORN / TAUNUS', 'CHAMBERY CEDEX', 'TORINO', 'TACHOV', 'BIANCONESE DE FONTEVIVO', 'UMMENDORF', 'HOMBURG/SAAR', 'THOUROTTE', 'DOBROVICE', 'OFFINGEN', 'HENNERSDORF', 'OSTROWIEC', 'BREITENBACH (HERZBERG)', 'KÄBSCHÜTZTAL', 'MARL-SINSEN', 'MONCALIETI', 'BIRKUNGEN', 'MAGDEBURG', 'ROTTLEBERODE', 'NORRKÖPING', 'NITTENAU', 'METTMANN', 'BUTTSTÄDT', 'LOHR A. MAIN', 'CHAMERAU', 'SATTELDORF', 'SASSNITZ-OT MUKRAN', 'LUCERNE', 'DINAZZANO (RE)', 'PRAHA 1', 'SAARLOUIS', 'WÖRGL', 'BEELEN', 'HAGEN-HOHENLIMBURG', 'TESTDORF'];
   getMockInfrastructureLocation () {
    const mockInfrastructureLocation:InfrastructureLocation = {
 
        authority: 80,
        // locationCode: type: string maxLength: 6 description: code of location for GPCP
        locationCode: '',
        // locationName: type: string maxLength: 35 description: name of location for GPCP
        locationName: this.getRandomArrayElement(this.mockCity)
       }
       return mockInfrastructureLocation;
   }
   
    private mockTrackingEventWagon(): WagonTrackingHistory {
        return  {
            trainNumber: '65074', // trainNumber: type: string example: '47111' 
            eventDateTime: this.getRandomDateWithinRange(this.getTomorrow(), this.getSixMonthsFromNow()),
            infrastructureLocation: this.getMockInfrastructureLocation(), // infrastructureLocation: $ref: '#/components/schemas/InfrastructureLocation'
            event: this.getRandomEventType() // event: $ref: '#/components/schemas/WagonEventType'
        }
    }

    private  getRandomEventType(): WagonEventType {
        const eventTypes = Object.values(WagonEventType);
        const randomIndex = Math.floor(Math.random() * eventTypes.length);
        return eventTypes[randomIndex] as WagonEventType;
    }
    
    private enumToStringArray<T>(enumObj: T): string[] {
        return Object.values(enumObj);
    }
    private stringToEnum<T>(enumObj: T, value: string): T[keyof T] | undefined {
        return (Object.values(enumObj) as string[]).includes(value) ? value as T[keyof T] : undefined;
    }

    private getTomorrow(): Date {
        const now = new Date();
        return new Date(now.getDay() + 1);
    }

    private getSixMonthsFromNow(): Date {
        const now = new Date();
        return new Date(now.setMonth(now.getMonth() + 6));
    }

    private getRandomDateWithinRange(start: Date, end: Date): string {
        const startTime = start.getTime();
        const endTime = end.getTime();
        return new Date(startTime + Math.random() * (endTime - startTime)).toISOString();
    }

    private getRandomArrayElement<T>(arr: T[]): T {
        const randomIndex = Math.floor(Math.random() * arr.length);
        return arr[randomIndex];
    }

    private wagonTrackingItems250() {

        for (let i = 0; i < 250; i++) {
            this.trackingHistoryWagon.push(this.mockTrackingEventWagon());
        }

        return this.trackingHistoryWagon;
    }

    public getStaticWagonSummaryResponse(): WagonTrackingHistory[] {

            return  this.wagonTrackingItems250()
        };
}