openapi: "3.0.2"

info:
  title: Invoice internal API
  version: 1.0.0
tags:
  - name: Invoice internal API

servers:
  - url: /api/inv/v1

paths:

  /invoices/debitors:
    get:
      tags:
        - Invoice internal API
      summary: Returns a list of debitors id and names
      operationId: getInvoiceDebitors
      parameters:
        - name: query
          in: query
          description: query string.
          required: true
          schema:
            type: string
      responses:
        200:
          description: An array of debitors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IdNameType'
        400:
          description: Bad Request. Invalid params supplied
          content:
            application/problem+json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/Problem'
        401:
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/Problem'
        500:
          description: Error(s) occurred while processing the request
          content:
            application/problem+json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/Problem'

  /invoices/types:
    get:
      tags:
        - Invoice internal API
      summary: Returns a list of invoice types
      operationId: getInvoiceTypes
      responses:
        200:
          description: An array of invoice types
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  enum:
                    - CPI
                    - SAP
        400:
          description: Bad Request. Invalid params supplied
          content:
            application/problem+json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/Problem'
        401:
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/Problem'
        500:
          description: Error(s) occurred while processing the request
          content:
            application/problem+json:
              schema:
                $ref: 'schemas.yaml#/components/schemas/Problem'
components:
  schemas:
    IdNameType:
      type: object
      properties:
        id:
          type: string
        name:
          type: string